[package]
name = "atomic-cli"
version = "0.5.0"
authors = ["Joep Meindertsma <joep@argu.co>"]
edition = "2018"
license = "MIT"
description = "CLI tool to create, store, query, validate and convert Atomic Data"
readme = "README.md"
repository = "https://github.com/joepio/atomic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
promptly = "0.3.0"
clap = "2.33.1"
colored = "1.9.3"
atomic_lib = { path = "../lib" }
uuid = {version = "0.8.1", features = ["v4"]}
dirs = "3.0.1"
regex = "1.3.9"
