[package]
name = "atomic"
version = "0.11.0"
description = "Create, share, fetch and model linked Atomic Data!"
license = "MIT"
repository = "https://github.com/joepio/atomic"

[[module]]
name = "atomic"
source = "../target/wasm32-wasi/release/atomic-cli.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "atomic"
module = "atomic-cli.wasm"
