[package]
name = "atomic-server"
description = "Create, share and standardize linked atomic data!"
version = "0.5.0"
authors = ["Joep Meindertsma <joep@ontola.io>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/joepio/atomic-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.56"
serde = { version = "1.0.114", features = ["derive"] }
uuid = {version = "0.8.1", features = ["v4"]}
regex = "1.3.9"
dirs = "3.0.1"
tokio = "0.2.22"
dotenv = "0.15.0"
actix-web = { version = "2.0.0", features=["rustls"] }
actix-rt = "1.1.1"
tera = "1.4.0"
actix-files = "0.2.2"
atomic_lib = { path = "../lib" }
